### PR TITLE
remove + ignore composer.lock + update league/oauth2-client to version 2

### PR DESCRIPTION
**Pull request by it-can**
remove + ignore composer.lock + update league/oauth2-client to version 2

### CODE REVIEW

**Comment by it-can** [comment]
@Edwin-Luijten can you take a look?

**Comment by Edwin-Luijten** [comment]
@it-can looks good, before I merge could you remove the actual lock file from the repository?

**Comment by it-can** [comment]
I deleted the lockfile...

**Comment by Edwin-Luijten** [comment]
bumped version to 1.2.0

**Pull request merged**
